name: Run linter

on:
  pull_request:
    branches:
      - main

jobs:
  lint-app:
    name: Linting
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.18

      - name: Install
        run: make install && make gomod

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
