name: Run tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-app:
    name: Running Tests
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: ^1.20
      - name: Install
        run: make install && make gomod
      - name: Build
        run: make build
      - name: Generated files
        run: |
          export PATH=$PATH:$(go env GOPATH)/bin
          make generate fmt
          git diff --exit-code --numstat
      - name: Run tests
        run: make test
